version: "3"

services:
  mysql:
    container_name: mysql-container
    image: mysql:5
    restart: always
    volumes:
      - ./data:/data/database
    ports:
      - "27017:27017"

  api:
    container_name: api-container
    build: .
    image: node:12
    working_dir: /usr/src/user-manager-api
    restart: always
    command: bash -c "npm install --only=prod && npm run debug"
    volumes:
      - ./dist:/usr/src/user-manager-api/dist
      - ./package.json:/usr/src/user-manager-api/package.json
    ports:
      - "5353:5353"
      - "9222:9222"
    links:
      - mysql