apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-manager
  labels:
    app: user-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-manager
  template:
    metadata:
      labels:
        app: user-manager
    spec:
      containers:
        - name: user-manager
          image: user-manager-api:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000

          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: user-config
                  key: PORT
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: user-config
                  key: DB_HOST
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: user-config
                  key: DB_USER
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: user-config
                  key: DB_NAME
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: user-config
                  key: DB_PORT

            # sensíveis -> Secret (recomendado)
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-secrets
                  key: DB_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: user-secrets
                  key: JWT_SECRET
            - name: RESEND_API_KEY
              valueFrom:
                secretKeyRef:
                  name: user-secrets
                  key: RESEND_API_KEY

          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 20

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
