apiVersion: v1
kind: Service
metadata:
  name: user-manager-service
spec:
  selector:
    app: user-manager
  type: NodePort
  ports:
    - name: http
      port: 5053
      targetPort: 5053
      nodePort: 30006
